language: node_js
node_js:
  - "6"
script:
  # generate website.
  - export NODE_ENV=production
  - node index.js
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: $SURGE_DOMAIN
  on:
    branch: master
cache:
  directories:
    - node_modules