language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
script:
  env:
    - NODE_ENV=production
  # generate website.
  - node index.js
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: $SURGE_DOMAIN
  on:
    branch: master