language: node_js
node_js:
  - "6"
git:
  depth: 3
script: .travis/build.sh
deploy:
  - provider: surge
    skip_cleanup: true
    project: ./build/
    #my surge domain doesn't need to be out in the open. doesn't matter if anyone finds it, though.
    domain: $SURGE_DOMAIN
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    on:
      branch: production
cache:
  directories:
    - node_modules